// Refreshes the cached homepage ledes in lib/startHere.data.ts from the live
// backend. Run on a nightly cron or before a release so the homepage stays
// current without fetching six companies on every load.
//
// Usage: node scripts/refreshStartHere.mjs
//
// This mirrors the lede logic in lib/summary/generateLede.ts. Keep the two in
// step: this script is plain ESM so it can run in CI without a TypeScript
// build step.

import { writeFileSync } from "node:fs";

const BACKEND =
  process.env.PIPELINE_API_URL ?? "https://dossier-api-kappa.vercel.app";

const COMPANIES = [
  { ticker: "AAPL", label: "Apple" },
  { ticker: "NVDA", label: "NVIDIA" },
  { ticker: "MSFT", label: "Microsoft" },
  { ticker: "PFE", label: "Pfizer" },
  { ticker: "TSLA", label: "Tesla" },
  { ticker: "MRNA", label: "Moderna" },
];

const SUFFIX = { CORP: "Corp", INC: "Inc", CO: "Co", HOLDINGS: "Holdings" };
const KEEP = new Set(["NVIDIA", "IBM", "AMD", "SAP"]);

/** Takes an EDGAR name. Returns a display form. */
function prettyName(name) {
  return name
    .split(/\s+/)
    .map((word) => {
      const bare = word.replace(/[.,]/g, "");
      const upper = bare.toUpperCase();
      if (SUFFIX[upper]) return SUFFIX[upper];
      if (KEEP.has(upper)) return bare;
      if (word !== word.toUpperCase()) return word;
      if (bare.length <= 2) return bare;
      return bare.charAt(0) + bare.slice(1).toLowerCase();
    })
    .join(" ");
}

const SOURCE_LABELS = {
  sec_edgar: "SEC EDGAR",
  openalex: "OpenAlex",
  clinicaltrials: "ClinicalTrials.gov",
  nih_reporter: "NIH RePORTER",
};
const SOURCE_NOUNS = {
  sec_edgar: "filing",
  openalex: "research paper",
  clinicaltrials: "trial",
  nih_reporter: "grant",
};
const WORDS = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"];

/** Takes a count and noun. Returns the contribution phrase. */
function contribution(source, count) {
  const noun = SOURCE_NOUNS[source] ?? "record";
  return `${count} ${count === 1 ? noun : noun + "s"}`;
}

/** Takes a record set. Returns the two to three sentence lede. */
function generateLede(entity, records) {
  const bySource = new Map();
  const years = [];
  for (const r of records) {
    bySource.set(r.source, (bySource.get(r.source) ?? 0) + 1);
    const y = Number(String(r.date).slice(0, 4));
    if (Number.isFinite(y) && y > 1900) years.push(y);
  }
  const sources = [...bySource.entries()]
    .map(([source, count]) => ({ source, count }))
    .sort((a, b) => b.count - a.count || a.source.localeCompare(b.source));
  const first = years.length ? Math.min(...years) : null;
  const last = years.length ? Math.max(...years) : null;

  const sourceWord = sources.length < WORDS.length ? WORDS[sources.length] : String(sources.length);
  const span = first && last ? (first === last ? ` in ${first}` : `, spanning ${first} to ${last}`) : "";
  const s1 = `${entity} has ${records.length} verified records across ${sourceWord} sources${span}.`;

  let s2 = "";
  if (sources.length >= 2) {
    s2 = ` The company is most active on ${SOURCE_LABELS[sources[0].source]} with ${contribution(
      sources[0].source,
      sources[0].count
    )}, followed by ${contribution(sources[1].source, sources[1].count)} from ${
      SOURCE_LABELS[sources[1].source]
    }.`;
  }
  return s1 + s2;
}

/** Fetches every company and writes the cached data module. */
async function main() {
  const rows = [];
  for (const c of COMPANIES) {
    const res = await fetch(`${BACKEND}/run`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ entity: c.ticker, ticker: c.ticker, max_results: 10 }),
    });
    const data = await res.json();
    const name = prettyName(data.profile?.name || c.label);
    rows.push({
      ticker: c.ticker,
      name,
      industry: data.profile?.industry ?? "",
      lede: generateLede(name, data.records ?? []),
    });
  }

  const body = `// Cached lede sentences for the homepage "start here" grid.
//
// Generated by scripts/refreshStartHere.mjs from the live backend so the
// homepage never fetches six companies on load. Regenerate on a nightly cron
// or before a release. Do not edit by hand.

import type { StartHereCard } from "./startHere.types";

export const START_HERE: StartHereCard[] = ${JSON.stringify(rows, null, 2)};
`;
  writeFileSync(new URL("../lib/startHere.data.ts", import.meta.url), body);
  console.log(`Wrote ${rows.length} cards to lib/startHere.data.ts`);
}

main();
