// Cached lede sentences for the homepage "start here" grid.
//
// Generated by scripts/refreshStartHere.mjs from the live backend so the
// homepage never fetches six companies on load. Regenerate on a nightly cron
// or before a release. Do not edit by hand.

import type { StartHereCard } from "./startHere.types";

export const START_HERE: StartHereCard[] = [
  {
    "ticker": "AAPL",
    "name": "Apple Inc",
    "industry": "Electronic Computers",
    "lede": "Apple Inc has 36 verified records across four sources, spanning 2009 to 2026. The company is most active on ClinicalTrials.gov with 10 trials, followed by 10 grants from NIH RePORTER. 2026 is the busiest year on record with 18 items, led by SEC filings."
  },
  {
    "ticker": "NVDA",
    "name": "NVIDIA Corp",
    "industry": "Semiconductors & Related Devices",
    "lede": "NVIDIA Corp has 26 verified records across four sources, spanning 2020 to 2026. The company is most active on OpenAlex with 10 research papers, followed by 9 grants from NIH RePORTER. 2026 is the busiest year on record with 17 items, led by research papers."
  },
  {
    "ticker": "MSFT",
    "name": "Microsoft Corp",
    "industry": "Services-Prepackaged Software",
    "lede": "Microsoft Corp has 31 verified records across four sources, spanning 1997 to 2026. The company is most active on ClinicalTrials.gov with 10 trials, followed by 8 research papers from OpenAlex. 2026 is the busiest year on record with 16 items, led by research papers."
  },
  {
    "ticker": "PFE",
    "name": "Pfizer Inc",
    "industry": "Pharmaceutical Preparations",
    "lede": "Pfizer Inc has 35 verified records across four sources, spanning 1997 to 2026. The company is most active on ClinicalTrials.gov with 10 trials, followed by 10 grants from NIH RePORTER. 2026 is the busiest year on record with 17 items, led by research papers."
  },
  {
    "ticker": "TSLA",
    "name": "Tesla, Inc",
    "industry": "Motor Vehicles & Passenger Car Bodies",
    "lede": "Tesla, Inc has 38 verified records across four sources, spanning 1997 to 2026. The company is most active on ClinicalTrials.gov with 10 trials, followed by 10 research papers from OpenAlex. 2026 is the busiest year on record with 21 items, led by SEC filings."
  },
  {
    "ticker": "MRNA",
    "name": "Moderna, Inc",
    "industry": "Biological Products, (No Diagnostic Substances)",
    "lede": "Moderna, Inc has 27 verified records across four sources, spanning 2015 to 2026. The company is most active on NIH RePORTER with 10 grants, followed by 10 filings from SEC EDGAR. 2026 is the busiest year on record with 17 items, led by SEC filings."
  }
];
