// Cached lede sentences for the homepage "start here" grid.
//
// Generated by scripts/refreshStartHere.mjs from the live backend so the
// homepage never fetches companies on load. Regenerate on a nightly cron or
// before a release. Do not edit by hand.

import type { StartHereCard } from "./startHere.types";

export const START_HERE: StartHereCard[] = [
  {
    "ticker": "AAPL",
    "name": "Apple Inc",
    "industry": "Electronic Computers",
    "lede": "Its researchers most recently published on Scaling Search Relevance: Augmenting App Store Ranking with LLM-Generated Judgments, in July 2026. Its most recent major filing is a quarterly report (10-Q), May 2026."
  },
  {
    "ticker": "MRNA",
    "name": "Moderna, Inc",
    "industry": "Biological Products, (No Diagnostic Substances)",
    "lede": "Its researchers most recently published on Structural basis of membrane engagement and polyreactivity control in HIV-1 MPER broadly…, in July 2026. Its most recent major filing is a current report (8-K), July 2026."
  },
  {
    "ticker": "NVDA",
    "name": "NVIDIA Corp",
    "industry": "Semiconductors & Related Devices",
    "lede": "Its researchers most recently published on Computational History and Heritage: New Enquiries Through Synthesis, in July 2026. Its most recent major filing is a current report (8-K), July 2026."
  }
];
